/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StocksRouteImport } from './routes/stocks'
import { Route as SallesSportRouteImport } from './routes/salles-sport'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RecettesRouteImport } from './routes/recettes'
import { Route as RapportsRouteImport } from './routes/rapports'
import { Route as PersonnelRouteImport } from './routes/personnel'
import { Route as ParametresRouteImport } from './routes/parametres'
import { Route as LoginRouteImport } from './routes/login'
import { Route as JournalCaisseRouteImport } from './routes/journal-caisse'
import { Route as HammamRouteImport } from './routes/hammam'
import { Route as FacturesRouteImport } from './routes/factures'
import { Route as EvenementsRouteImport } from './routes/evenements'
import { Route as DevisRouteImport } from './routes/devis'
import { Route as DepensesRouteImport } from './routes/depenses'
import { Route as ClientsRouteImport } from './routes/clients'
import { Route as AppartementsRouteImport } from './routes/appartements'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HooksQuittancesMensuellesRouteImport } from './routes/hooks/quittances-mensuelles'
import { Route as HooksPenalitesRappelsRouteImport } from './routes/hooks/penalites-rappels'
import { Route as HooksClotureJournalRouteImport } from './routes/hooks/cloture-journal'
import { Route as HooksBilanMensuelRouteImport } from './routes/hooks/bilan-mensuel'

const StocksRoute = StocksRouteImport.update({
  id: '/stocks',
  path: '/stocks',
  getParentRoute: () => rootRouteImport,
} as any)
const SallesSportRoute = SallesSportRouteImport.update({
  id: '/salles-sport',
  path: '/salles-sport',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RecettesRoute = RecettesRouteImport.update({
  id: '/recettes',
  path: '/recettes',
  getParentRoute: () => rootRouteImport,
} as any)
const RapportsRoute = RapportsRouteImport.update({
  id: '/rapports',
  path: '/rapports',
  getParentRoute: () => rootRouteImport,
} as any)
const PersonnelRoute = PersonnelRouteImport.update({
  id: '/personnel',
  path: '/personnel',
  getParentRoute: () => rootRouteImport,
} as any)
const ParametresRoute = ParametresRouteImport.update({
  id: '/parametres',
  path: '/parametres',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const JournalCaisseRoute = JournalCaisseRouteImport.update({
  id: '/journal-caisse',
  path: '/journal-caisse',
  getParentRoute: () => rootRouteImport,
} as any)
const HammamRoute = HammamRouteImport.update({
  id: '/hammam',
  path: '/hammam',
  getParentRoute: () => rootRouteImport,
} as any)
const FacturesRoute = FacturesRouteImport.update({
  id: '/factures',
  path: '/factures',
  getParentRoute: () => rootRouteImport,
} as any)
const EvenementsRoute = EvenementsRouteImport.update({
  id: '/evenements',
  path: '/evenements',
  getParentRoute: () => rootRouteImport,
} as any)
const DevisRoute = DevisRouteImport.update({
  id: '/devis',
  path: '/devis',
  getParentRoute: () => rootRouteImport,
} as any)
const DepensesRoute = DepensesRouteImport.update({
  id: '/depenses',
  path: '/depenses',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientsRoute = ClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => rootRouteImport,
} as any)
const AppartementsRoute = AppartementsRouteImport.update({
  id: '/appartements',
  path: '/appartements',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HooksQuittancesMensuellesRoute =
  HooksQuittancesMensuellesRouteImport.update({
    id: '/hooks/quittances-mensuelles',
    path: '/hooks/quittances-mensuelles',
    getParentRoute: () => rootRouteImport,
  } as any)
const HooksPenalitesRappelsRoute = HooksPenalitesRappelsRouteImport.update({
  id: '/hooks/penalites-rappels',
  path: '/hooks/penalites-rappels',
  getParentRoute: () => rootRouteImport,
} as any)
const HooksClotureJournalRoute = HooksClotureJournalRouteImport.update({
  id: '/hooks/cloture-journal',
  path: '/hooks/cloture-journal',
  getParentRoute: () => rootRouteImport,
} as any)
const HooksBilanMensuelRoute = HooksBilanMensuelRouteImport.update({
  id: '/hooks/bilan-mensuel',
  path: '/hooks/bilan-mensuel',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/appartements': typeof AppartementsRoute
  '/clients': typeof ClientsRoute
  '/depenses': typeof DepensesRoute
  '/devis': typeof DevisRoute
  '/evenements': typeof EvenementsRoute
  '/factures': typeof FacturesRoute
  '/hammam': typeof HammamRoute
  '/journal-caisse': typeof JournalCaisseRoute
  '/login': typeof LoginRoute
  '/parametres': typeof ParametresRoute
  '/personnel': typeof PersonnelRoute
  '/rapports': typeof RapportsRoute
  '/recettes': typeof RecettesRoute
  '/reset-password': typeof ResetPasswordRoute
  '/salles-sport': typeof SallesSportRoute
  '/stocks': typeof StocksRoute
  '/hooks/bilan-mensuel': typeof HooksBilanMensuelRoute
  '/hooks/cloture-journal': typeof HooksClotureJournalRoute
  '/hooks/penalites-rappels': typeof HooksPenalitesRappelsRoute
  '/hooks/quittances-mensuelles': typeof HooksQuittancesMensuellesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/appartements': typeof AppartementsRoute
  '/clients': typeof ClientsRoute
  '/depenses': typeof DepensesRoute
  '/devis': typeof DevisRoute
  '/evenements': typeof EvenementsRoute
  '/factures': typeof FacturesRoute
  '/hammam': typeof HammamRoute
  '/journal-caisse': typeof JournalCaisseRoute
  '/login': typeof LoginRoute
  '/parametres': typeof ParametresRoute
  '/personnel': typeof PersonnelRoute
  '/rapports': typeof RapportsRoute
  '/recettes': typeof RecettesRoute
  '/reset-password': typeof ResetPasswordRoute
  '/salles-sport': typeof SallesSportRoute
  '/stocks': typeof StocksRoute
  '/hooks/bilan-mensuel': typeof HooksBilanMensuelRoute
  '/hooks/cloture-journal': typeof HooksClotureJournalRoute
  '/hooks/penalites-rappels': typeof HooksPenalitesRappelsRoute
  '/hooks/quittances-mensuelles': typeof HooksQuittancesMensuellesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/appartements': typeof AppartementsRoute
  '/clients': typeof ClientsRoute
  '/depenses': typeof DepensesRoute
  '/devis': typeof DevisRoute
  '/evenements': typeof EvenementsRoute
  '/factures': typeof FacturesRoute
  '/hammam': typeof HammamRoute
  '/journal-caisse': typeof JournalCaisseRoute
  '/login': typeof LoginRoute
  '/parametres': typeof ParametresRoute
  '/personnel': typeof PersonnelRoute
  '/rapports': typeof RapportsRoute
  '/recettes': typeof RecettesRoute
  '/reset-password': typeof ResetPasswordRoute
  '/salles-sport': typeof SallesSportRoute
  '/stocks': typeof StocksRoute
  '/hooks/bilan-mensuel': typeof HooksBilanMensuelRoute
  '/hooks/cloture-journal': typeof HooksClotureJournalRoute
  '/hooks/penalites-rappels': typeof HooksPenalitesRappelsRoute
  '/hooks/quittances-mensuelles': typeof HooksQuittancesMensuellesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/appartements'
    | '/clients'
    | '/depenses'
    | '/devis'
    | '/evenements'
    | '/factures'
    | '/hammam'
    | '/journal-caisse'
    | '/login'
    | '/parametres'
    | '/personnel'
    | '/rapports'
    | '/recettes'
    | '/reset-password'
    | '/salles-sport'
    | '/stocks'
    | '/hooks/bilan-mensuel'
    | '/hooks/cloture-journal'
    | '/hooks/penalites-rappels'
    | '/hooks/quittances-mensuelles'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/appartements'
    | '/clients'
    | '/depenses'
    | '/devis'
    | '/evenements'
    | '/factures'
    | '/hammam'
    | '/journal-caisse'
    | '/login'
    | '/parametres'
    | '/personnel'
    | '/rapports'
    | '/recettes'
    | '/reset-password'
    | '/salles-sport'
    | '/stocks'
    | '/hooks/bilan-mensuel'
    | '/hooks/cloture-journal'
    | '/hooks/penalites-rappels'
    | '/hooks/quittances-mensuelles'
  id:
    | '__root__'
    | '/'
    | '/appartements'
    | '/clients'
    | '/depenses'
    | '/devis'
    | '/evenements'
    | '/factures'
    | '/hammam'
    | '/journal-caisse'
    | '/login'
    | '/parametres'
    | '/personnel'
    | '/rapports'
    | '/recettes'
    | '/reset-password'
    | '/salles-sport'
    | '/stocks'
    | '/hooks/bilan-mensuel'
    | '/hooks/cloture-journal'
    | '/hooks/penalites-rappels'
    | '/hooks/quittances-mensuelles'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppartementsRoute: typeof AppartementsRoute
  ClientsRoute: typeof ClientsRoute
  DepensesRoute: typeof DepensesRoute
  DevisRoute: typeof DevisRoute
  EvenementsRoute: typeof EvenementsRoute
  FacturesRoute: typeof FacturesRoute
  HammamRoute: typeof HammamRoute
  JournalCaisseRoute: typeof JournalCaisseRoute
  LoginRoute: typeof LoginRoute
  ParametresRoute: typeof ParametresRoute
  PersonnelRoute: typeof PersonnelRoute
  RapportsRoute: typeof RapportsRoute
  RecettesRoute: typeof RecettesRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SallesSportRoute: typeof SallesSportRoute
  StocksRoute: typeof StocksRoute
  HooksBilanMensuelRoute: typeof HooksBilanMensuelRoute
  HooksClotureJournalRoute: typeof HooksClotureJournalRoute
  HooksPenalitesRappelsRoute: typeof HooksPenalitesRappelsRoute
  HooksQuittancesMensuellesRoute: typeof HooksQuittancesMensuellesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/stocks': {
      id: '/stocks'
      path: '/stocks'
      fullPath: '/stocks'
      preLoaderRoute: typeof StocksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/salles-sport': {
      id: '/salles-sport'
      path: '/salles-sport'
      fullPath: '/salles-sport'
      preLoaderRoute: typeof SallesSportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recettes': {
      id: '/recettes'
      path: '/recettes'
      fullPath: '/recettes'
      preLoaderRoute: typeof RecettesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rapports': {
      id: '/rapports'
      path: '/rapports'
      fullPath: '/rapports'
      preLoaderRoute: typeof RapportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/personnel': {
      id: '/personnel'
      path: '/personnel'
      fullPath: '/personnel'
      preLoaderRoute: typeof PersonnelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parametres': {
      id: '/parametres'
      path: '/parametres'
      fullPath: '/parametres'
      preLoaderRoute: typeof ParametresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journal-caisse': {
      id: '/journal-caisse'
      path: '/journal-caisse'
      fullPath: '/journal-caisse'
      preLoaderRoute: typeof JournalCaisseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hammam': {
      id: '/hammam'
      path: '/hammam'
      fullPath: '/hammam'
      preLoaderRoute: typeof HammamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/factures': {
      id: '/factures'
      path: '/factures'
      fullPath: '/factures'
      preLoaderRoute: typeof FacturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/evenements': {
      id: '/evenements'
      path: '/evenements'
      fullPath: '/evenements'
      preLoaderRoute: typeof EvenementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/devis': {
      id: '/devis'
      path: '/devis'
      fullPath: '/devis'
      preLoaderRoute: typeof DevisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/depenses': {
      id: '/depenses'
      path: '/depenses'
      fullPath: '/depenses'
      preLoaderRoute: typeof DepensesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clients': {
      id: '/clients'
      path: '/clients'
      fullPath: '/clients'
      preLoaderRoute: typeof ClientsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/appartements': {
      id: '/appartements'
      path: '/appartements'
      fullPath: '/appartements'
      preLoaderRoute: typeof AppartementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hooks/quittances-mensuelles': {
      id: '/hooks/quittances-mensuelles'
      path: '/hooks/quittances-mensuelles'
      fullPath: '/hooks/quittances-mensuelles'
      preLoaderRoute: typeof HooksQuittancesMensuellesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hooks/penalites-rappels': {
      id: '/hooks/penalites-rappels'
      path: '/hooks/penalites-rappels'
      fullPath: '/hooks/penalites-rappels'
      preLoaderRoute: typeof HooksPenalitesRappelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hooks/cloture-journal': {
      id: '/hooks/cloture-journal'
      path: '/hooks/cloture-journal'
      fullPath: '/hooks/cloture-journal'
      preLoaderRoute: typeof HooksClotureJournalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hooks/bilan-mensuel': {
      id: '/hooks/bilan-mensuel'
      path: '/hooks/bilan-mensuel'
      fullPath: '/hooks/bilan-mensuel'
      preLoaderRoute: typeof HooksBilanMensuelRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppartementsRoute: AppartementsRoute,
  ClientsRoute: ClientsRoute,
  DepensesRoute: DepensesRoute,
  DevisRoute: DevisRoute,
  EvenementsRoute: EvenementsRoute,
  FacturesRoute: FacturesRoute,
  HammamRoute: HammamRoute,
  JournalCaisseRoute: JournalCaisseRoute,
  LoginRoute: LoginRoute,
  ParametresRoute: ParametresRoute,
  PersonnelRoute: PersonnelRoute,
  RapportsRoute: RapportsRoute,
  RecettesRoute: RecettesRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SallesSportRoute: SallesSportRoute,
  StocksRoute: StocksRoute,
  HooksBilanMensuelRoute: HooksBilanMensuelRoute,
  HooksClotureJournalRoute: HooksClotureJournalRoute,
  HooksPenalitesRappelsRoute: HooksPenalitesRappelsRoute,
  HooksQuittancesMensuellesRoute: HooksQuittancesMensuellesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
