/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SallesSportRouteImport } from './routes/salles-sport'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RecettesRouteImport } from './routes/recettes'
import { Route as RapportsRouteImport } from './routes/rapports'
import { Route as ParametresRouteImport } from './routes/parametres'
import { Route as LoginRouteImport } from './routes/login'
import { Route as JournalCaisseRouteImport } from './routes/journal-caisse'
import { Route as HammamRouteImport } from './routes/hammam'
import { Route as EvenementsRouteImport } from './routes/evenements'
import { Route as DepensesRouteImport } from './routes/depenses'
import { Route as AppartementsRouteImport } from './routes/appartements'
import { Route as IndexRouteImport } from './routes/index'

const SallesSportRoute = SallesSportRouteImport.update({
  id: '/salles-sport',
  path: '/salles-sport',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RecettesRoute = RecettesRouteImport.update({
  id: '/recettes',
  path: '/recettes',
  getParentRoute: () => rootRouteImport,
} as any)
const RapportsRoute = RapportsRouteImport.update({
  id: '/rapports',
  path: '/rapports',
  getParentRoute: () => rootRouteImport,
} as any)
const ParametresRoute = ParametresRouteImport.update({
  id: '/parametres',
  path: '/parametres',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const JournalCaisseRoute = JournalCaisseRouteImport.update({
  id: '/journal-caisse',
  path: '/journal-caisse',
  getParentRoute: () => rootRouteImport,
} as any)
const HammamRoute = HammamRouteImport.update({
  id: '/hammam',
  path: '/hammam',
  getParentRoute: () => rootRouteImport,
} as any)
const EvenementsRoute = EvenementsRouteImport.update({
  id: '/evenements',
  path: '/evenements',
  getParentRoute: () => rootRouteImport,
} as any)
const DepensesRoute = DepensesRouteImport.update({
  id: '/depenses',
  path: '/depenses',
  getParentRoute: () => rootRouteImport,
} as any)
const AppartementsRoute = AppartementsRouteImport.update({
  id: '/appartements',
  path: '/appartements',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/appartements': typeof AppartementsRoute
  '/depenses': typeof DepensesRoute
  '/evenements': typeof EvenementsRoute
  '/hammam': typeof HammamRoute
  '/journal-caisse': typeof JournalCaisseRoute
  '/login': typeof LoginRoute
  '/parametres': typeof ParametresRoute
  '/rapports': typeof RapportsRoute
  '/recettes': typeof RecettesRoute
  '/reset-password': typeof ResetPasswordRoute
  '/salles-sport': typeof SallesSportRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/appartements': typeof AppartementsRoute
  '/depenses': typeof DepensesRoute
  '/evenements': typeof EvenementsRoute
  '/hammam': typeof HammamRoute
  '/journal-caisse': typeof JournalCaisseRoute
  '/login': typeof LoginRoute
  '/parametres': typeof ParametresRoute
  '/rapports': typeof RapportsRoute
  '/recettes': typeof RecettesRoute
  '/reset-password': typeof ResetPasswordRoute
  '/salles-sport': typeof SallesSportRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/appartements': typeof AppartementsRoute
  '/depenses': typeof DepensesRoute
  '/evenements': typeof EvenementsRoute
  '/hammam': typeof HammamRoute
  '/journal-caisse': typeof JournalCaisseRoute
  '/login': typeof LoginRoute
  '/parametres': typeof ParametresRoute
  '/rapports': typeof RapportsRoute
  '/recettes': typeof RecettesRoute
  '/reset-password': typeof ResetPasswordRoute
  '/salles-sport': typeof SallesSportRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/appartements'
    | '/depenses'
    | '/evenements'
    | '/hammam'
    | '/journal-caisse'
    | '/login'
    | '/parametres'
    | '/rapports'
    | '/recettes'
    | '/reset-password'
    | '/salles-sport'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/appartements'
    | '/depenses'
    | '/evenements'
    | '/hammam'
    | '/journal-caisse'
    | '/login'
    | '/parametres'
    | '/rapports'
    | '/recettes'
    | '/reset-password'
    | '/salles-sport'
  id:
    | '__root__'
    | '/'
    | '/appartements'
    | '/depenses'
    | '/evenements'
    | '/hammam'
    | '/journal-caisse'
    | '/login'
    | '/parametres'
    | '/rapports'
    | '/recettes'
    | '/reset-password'
    | '/salles-sport'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppartementsRoute: typeof AppartementsRoute
  DepensesRoute: typeof DepensesRoute
  EvenementsRoute: typeof EvenementsRoute
  HammamRoute: typeof HammamRoute
  JournalCaisseRoute: typeof JournalCaisseRoute
  LoginRoute: typeof LoginRoute
  ParametresRoute: typeof ParametresRoute
  RapportsRoute: typeof RapportsRoute
  RecettesRoute: typeof RecettesRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SallesSportRoute: typeof SallesSportRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/salles-sport': {
      id: '/salles-sport'
      path: '/salles-sport'
      fullPath: '/salles-sport'
      preLoaderRoute: typeof SallesSportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recettes': {
      id: '/recettes'
      path: '/recettes'
      fullPath: '/recettes'
      preLoaderRoute: typeof RecettesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rapports': {
      id: '/rapports'
      path: '/rapports'
      fullPath: '/rapports'
      preLoaderRoute: typeof RapportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parametres': {
      id: '/parametres'
      path: '/parametres'
      fullPath: '/parametres'
      preLoaderRoute: typeof ParametresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journal-caisse': {
      id: '/journal-caisse'
      path: '/journal-caisse'
      fullPath: '/journal-caisse'
      preLoaderRoute: typeof JournalCaisseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hammam': {
      id: '/hammam'
      path: '/hammam'
      fullPath: '/hammam'
      preLoaderRoute: typeof HammamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/evenements': {
      id: '/evenements'
      path: '/evenements'
      fullPath: '/evenements'
      preLoaderRoute: typeof EvenementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/depenses': {
      id: '/depenses'
      path: '/depenses'
      fullPath: '/depenses'
      preLoaderRoute: typeof DepensesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/appartements': {
      id: '/appartements'
      path: '/appartements'
      fullPath: '/appartements'
      preLoaderRoute: typeof AppartementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppartementsRoute: AppartementsRoute,
  DepensesRoute: DepensesRoute,
  EvenementsRoute: EvenementsRoute,
  HammamRoute: HammamRoute,
  JournalCaisseRoute: JournalCaisseRoute,
  LoginRoute: LoginRoute,
  ParametresRoute: ParametresRoute,
  RapportsRoute: RapportsRoute,
  RecettesRoute: RecettesRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SallesSportRoute: SallesSportRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
