-- app_settings : identité fiscale + cotisations complètes
ALTER TABLE public.app_settings
  ADD COLUMN IF NOT EXISTS niu TEXT,
  ADD COLUMN IF NOT EXISTS rccm TEXT,
  ADD COLUMN IF NOT EXISTS adresse TEXT,
  ADD COLUMN IF NOT EXISTS telephone TEXT,
  ADD COLUMN IF NOT EXISTS email_societe TEXT,
  ADD COLUMN IF NOT EXISTS regime_fiscal TEXT NOT NULL DEFAULT 'reel',
  ADD COLUMN IF NOT EXISTS secteur_at TEXT NOT NULL DEFAULT 'B',
  ADD COLUMN IF NOT EXISTS taux_at NUMERIC NOT NULL DEFAULT 2.5,
  ADD COLUMN IF NOT EXISTS taux_cfc_emp NUMERIC NOT NULL DEFAULT 1.0,
  ADD COLUMN IF NOT EXISTS taux_cfc_pat NUMERIC NOT NULL DEFAULT 1.5,
  ADD COLUMN IF NOT EXISTS taux_fne NUMERIC NOT NULL DEFAULT 1.0,
  ADD COLUMN IF NOT EXISTS plafond_cnps NUMERIC NOT NULL DEFAULT 750000;

-- clients : NIU
ALTER TABLE public.clients
  ADD COLUMN IF NOT EXISTS niu TEXT;

-- employes : matricule CNPS + NIU
ALTER TABLE public.employes
  ADD COLUMN IF NOT EXISTS matricule_cnps TEXT,
  ADD COLUMN IF NOT EXISTS niu_employe TEXT;

-- bulletins_paie : cotisations complètes + présence
ALTER TABLE public.bulletins_paie
  ADD COLUMN IF NOT EXISTS accidents_travail NUMERIC NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS cfc_employe NUMERIC NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS cfc_employeur NUMERIC NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS fne_employeur NUMERIC NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS rav NUMERIC NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS tdl NUMERIC NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS jours_travailles INTEGER,
  ADD COLUMN IF NOT EXISTS heures_normales NUMERIC NOT NULL DEFAULT 0;